# -*- coding: utf-8 -*-
"""IDS(1).ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1PnHRclp-hnJtfP8RHKXRnMsi9A_7B1BR
"""

import pandas as pd

df = pd.read_csv(
    "IDS(BTP)/nsl-kdd/KDDTrain+.csv",
    low_memory=False
)



df.columns

df.drop(columns=["difficulty"], inplace=True)

df["label"] = df["label"].apply(
    lambda x: "normal" if x == "normal" else "attack"
)

df = pd.get_dummies(
    df,
    columns=["protocol_type", "service", "flag"]
)

df["label"] = df["label"].map({"normal": 0, "attack": 1})

X = df.drop("label", axis=1)
y = df["label"]

X.dtypes[X.dtypes == "object"]

from sklearn.preprocessing import StandardScaler

scaler = StandardScaler()
X_scaled = scaler.fit_transform(X)

from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(
    X_scaled,
    y,
    test_size=0.2,
    random_state=42,
    stratify=y
)

from sklearn.ensemble import RandomForestClassifier

model = RandomForestClassifier(
    n_estimators=100,
    random_state=42,
    n_jobs=-1
)

model.fit(X_train, y_train)

y_pred = model.predict(X_test)

from sklearn.metrics import accuracy_score

accuracy = accuracy_score(y_test, y_pred)
print("Accuracy:", accuracy)

from sklearn.metrics import confusion_matrix

cm = confusion_matrix(y_test, y_pred)
print(cm)

from sklearn.metrics import classification_report

print(classification_report(y_test, y_pred))

from sklearn.metrics import roc_auc_score, roc_curve

y_prob = model.predict_proba(X_test)[:, 1]
roc_auc = roc_auc_score(y_test, y_prob)

print("ROC AUC:", roc_auc)

import pandas as pd

feature_importance = pd.Series(
    model.feature_importances_,
    index=X.columns
).sort_values(ascending=False)

print(feature_importance.head(15))

import joblib

joblib.dump(model, "ids_random_forest.pkl")
joblib.dump(scaler, "scaler.pkl")
joblib.dump(X.columns.tolist(), "feature_columns.pkl")
print("Feature columns saved:", len(X.columns))
print("Model and scaler saved")

loaded_model = joblib.load("ids_random_forest.pkl")
loaded_scaler = joblib.load("scaler.pkl")

sample = X.iloc[0:1]
sample_scaled = loaded_scaler.transform(sample)

prediction = loaded_model.predict(sample_scaled)
print("Prediction:", "Attack" if prediction[0] == 1 else "Normal")

# Normal traffic sample
X[y == 0].iloc[0:1].to_csv("normal_test.csv", index=False)

# Attack traffic sample
X[y == 1].iloc[0:1].to_csv("attack_test.csv", index=False)

print("CSV files created")

mixed_test = pd.concat([
    X[y == 0].iloc[:3],  # normal
    X[y == 1].iloc[:3]   # attack
])

mixed_test.to_csv("mixed_test.csv", index=False)
